Repository astropy/astroquery, pull requests merged in 2018-08, with the labels that each got.

#1218 Pin mpl to previous build as latest one doesn't work with np 1.9
  .travis.yml
Labels: infrastructure, no-changelog-entry-needed

#1216 Update SIMBAD votable fields
  astroquery/simbad/data/votable_fields_dict.json
  astroquery/simbad/get_votable_fields.py
  astroquery/simbad/tests/test_simbad.py
Labels: Upstream, no-changelog-entry-needed, simbad

#1199 Add docstring and signature for login
  CHANGES
  astroquery/mast/core.py
  astroquery/query.py
Labels: infrastructure, no-changelog-entry-needed

#1207 JPLHorizons update (re-submit)
  CHANGES
  astroquery/jplhorizons/__init__.py
  astroquery/jplhorizons/core.py
  astroquery/jplhorizons/tests/test_jplhorizons.py
  astroquery/jplhorizons/tests/test_jplhorizons_remote.py
  docs/jplhorizons/jplhorizons.rst
Labels: jplhorizons

#1220 Making description less ambiguous
  setup.cfg
Labels: Documentation, no-changelog-entry-needed

#1079 Refactor the Gallery
  docs/gallery-examples/example10_mast.py
  docs/gallery-examples/example1_vizier.py
  docs/gallery-examples/example2_simbad.py
  docs/gallery-examples/example3_simbad.py
  docs/gallery-examples/example4_simbad.py
  docs/gallery-examples/example5_oec.py
  docs/gallery-examples/example6_alma.py
  docs/gallery-examples/example7_alma.py
  docs/gallery-examples/example8_eso.py
  docs/gallery-examples/example9_skyview_vizier.py
  docs/gallery-examples/run_examples.py
  docs/gallery.rst
  setup.cfg
Labels: Documentation, no-changelog-entry-needed
