Repository astropy/astroquery, pull requests merged in 2019-10, with the labels that each got.

#1563 Fix Example 6 formatting
  docs/gallery-examples/example6_alma.py
Labels: Documentation, no-changelog-entry-needed

#1569 Docsbuild fix sphinx and numpydoc
  astroquery/nasa_exoplanet_archive/nasa_exoplanet_archive.py
  docs/conf.py
Labels: bug, infrastructure, merge-when-ci-passes, no-changelog-entry-needed

#1570 Fixing field_help mocking for SDSS and other small fixes to xmatch and ogle
  astroquery/ogle/core.py
  astroquery/sdss/core.py
  astroquery/sdss/field_names.py
  astroquery/sdss/tests/test_sdss.py
  astroquery/xmatch/core.py
Labels: no-changelog-entry-needed, ogle, sdss, xmatch

#1561 MAST: Add kepler to cloud accessable missions
  CHANGES.rst
  astroquery/mast/core.py
  astroquery/mast/fpl.py
  docs/mast/mast.rst
Labels: mast

#1560 Removing python2 testing and it's mention in the install docs and readme
  .travis.yml
  README.rst
  docs/index.rst
Labels: infrastructure, no-changelog-entry-needed

#1508 Move timer functions from astropy
  CHANGES.rst
  astroquery/utils/tests/test_timer.py
  astroquery/utils/timer.py
  astroquery/vo_conesearch/conesearch.py
  astroquery/vo_conesearch/validator/validate.py
  docs/_static/timer_prediction_pow10.png
  docs/utils.rst
Labels: utils

#1505 Create CASDA astroquery module
  CHANGES.rst
  astroquery/casda/__init__.py
  astroquery/casda/core.py
  astroquery/casda/tests/__init__.py
  astroquery/casda/tests/data/box.xml
  astroquery/casda/tests/data/cone.xml
  astroquery/casda/tests/setup_package.py
  astroquery/casda/tests/test_casda.py
  astroquery/casda/tests/test_casda_remote.py
  docs/casda/casda.rst
  docs/index.rst
Labels: New Service
