Repository astropy/astroquery, pull requests merged in 2021-05, with the labels that each got.

#2060 MNT: Remove pytest.ini
  astroquery/conftest.py
  astroquery/nasa_exoplanet_archive/core.py
  pytest.ini
  setup.cfg
Labels: bug, testing

#2059 TST: Fix vo_conesearch test failures
  astroquery/utils/commons.py
  astroquery/utils/tests/test_utils.py
Labels: bug, testing, vo_conesearch

#2056 Preparing for release v0.4.2
  CHANGES.rst
  astroquery/alma/tests/setup_package.py
  astroquery/cds/tests/test_mocserver.py
  astroquery/conftest.py
  astroquery/imcce/tests/test_skybot.py
  docs/index.rst
  docs/vamdc/vamdc.rst
  setup.cfg
  tox.ini
Labels: infrastructure, no-changelog-entry-needed, testing

#2071 Remove astroquery.lcogt
  CHANGES.rst
  astroquery/lcogt/__init__.py
  astroquery/lcogt/core.py
  astroquery/lcogt/tests/__init__.py
  astroquery/lcogt/tests/data/Box.xml
  astroquery/lcogt/tests/data/Cone.xml
  astroquery/lcogt/tests/data/Cone_coord.xml
  astroquery/lcogt/tests/data/Polygon.xml
  astroquery/lcogt/tests/setup_package.py
  astroquery/lcogt/tests/test_lcogt.py
  astroquery/lcogt/tests/test_lcogt_remote.py
  setup.cfg
Labels: lco

#2070 Deprecate astroquery.vamdc
  CHANGES.rst
  astroquery/vamdc/core.py
  astroquery/vamdc/tests/test_vamdc.py
  astroquery/vamdc/tests/test_vamdc_remote.py
  setup.cfg
Labels: vamdc

#2073 Fix alphabetical order of catalog list
  docs/index.rst
Labels: Documentation, no-changelog-entry-needed
