Repository astropy/astroquery, pull requests merged in 2023-10, with the labels that each got.

#2844 DOC: adding classifiers and fix urls
  setup.cfg
Labels: no-changelog-entry-needed

#2846 TST: Use Python 3.12 stable
  .github/workflows/ci_devtests.yml
Labels: infrastructure, no-changelog-entry-needed

#2853 MAINT: adding warning filter for numpy._core rename
  setup.cfg
Labels: infrastructure, no-changelog-entry-needed

#2854 TST: remove skip for BOX search as backend supports it again
  astroquery/ipac/irsa/tests/test_irsa_remote.py
Labels: testing, ipac.irsa, no-changelog-entry-needed

#2857 Update documentation to address `obsid` and `obs_id` db fields
  CHANGES.rst
  astroquery/mast/observations.py
  docs/mast/mast_obsquery.rst
Labels: Documentation, no-changelog-entry-needed, mast

#2860 Fixed a typo in README.rst
  README.rst
Labels: Documentation, no-changelog-entry-needed

#2862 fix typos in function definition helper text in python files of directory astroquery/mast/collections.py
  astroquery/mast/collections.py
  astroquery/mast/discovery_portal.py
  astroquery/mast/missions.py
  astroquery/mast/observations.py
  astroquery/mast/services.py
Labels: Documentation, no-changelog-entry-needed

#2842 Fix heasarc tests
  astroquery/heasarc/tests/conftest.py
  astroquery/heasarc/tests/data/404652d5.dat
  astroquery/heasarc/tests/data/4511b20b.dat
  astroquery/heasarc/tests/data/6ad7a587.dat
  astroquery/heasarc/tests/data/6df5af53.dat
  astroquery/heasarc/tests/data/f6d793e8.dat
  astroquery/heasarc/tests/data/ff1f8d6a.dat
  astroquery/heasarc/tests/data/last-month-integral_rev3_scw.dat
  astroquery/heasarc/tests/test_heasarc_remote.py
  astroquery/heasarc/tests/test_heasarc_remote_isdc.py
Labels: heasarc, no-changelog-entry-needed

#2861 DEP: votable.tree.Table was renamed to TableElement
  astroquery/cadc/tests/test_cadctap.py
  astroquery/vo_conesearch/conesearch.py
  astroquery/vo_conesearch/core.py
  astroquery/vo_conesearch/vos_catalog.py
  docs/conf.py
  docs/vo_conesearch/client.rst
Labels: no-changelog-entry-needed
