Repository astropy/astroquery, pull requests merged in 2023-05, with the labels that each got.

#2727 Fixed failing PANSTARRS `Catalog` queries
  CHANGES.rst
  astroquery/mast/collections.py
  astroquery/mast/services.py
  astroquery/mast/tests/test_mast_remote.py
Labels: bug, mast

#2732 CI: fix RTD build
  .readthedocs.yaml
Labels: infrastructure, no-changelog-entry-needed

#2737 Removing references to https://mast-labs.stsci.io website
  astroquery/mast/observations.py
Labels: Documentation, mast

#2740 TEST: using new continue on failure mode of doctestplus
  setup.cfg
Labels: testing, no-changelog-entry-needed

#2741 CI: updating URL of nightly wheels
  tox.ini
Labels: testing, no-changelog-entry-needed
